kumuluzee:
  name: orders-service
  version: 1.0.0
  server:
    base-url: http://localhost:3001
    http:
      port: 3001

  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      pool:
        max-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/BooksDS
    metrics:
      web-instrumentation:
        - name: metricsEndpoint
          url-pattern: /metrics/*
        - name: ordersEndpoint
          url-pattern: /orders/*

rest-properties:
    maintenance-mode: false
    broken: false
